# Linear Algebra Worksheet

### Please do these exercises by hand first. After you are done with your work, check your answers with Python

In [2]:
import numpy as np
import pandas as pd

In [3]:
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])
w = np.array([1,8,0,5])

## 1. Matrix Dimensions

**A**: 2 by 3  
**B**: 2 by 2  
**C**: 3 by 2   
**D**: 2 by 3  
**u**: 1 by 4    
**v**: 1 by 4  
**w**: 4 by 1  
  
For vectors, numpy array types don't really distinguish row vs. column vectors

In [10]:
print "A = \n", A, "\nwith shape  ", A.shape
print "B = \n", B, "\nwith shape  ", B.shape
print "C = \n", C, "\nwith shape  ", C.shape
print "D = \n", D, "\nwith shape  ", D.shape
print "u = \n", u, "\nwith shape  ", u.shape
print "v = \n", v, "\nwith shape  ", v.shape
print "w = \n", w, "\nwith shape  ", w.shape

A = 
[[1 2 3]
 [2 7 4]] 
with shape   (2, 3)
B = 
[[ 1 -1]
 [ 0  1]] 
with shape   (2, 2)
C = 
[[ 5 -1]
 [ 9  1]
 [ 6  0]] 
with shape   (3, 2)
D = 
[[ 3 -2 -1]
 [ 1  2  3]] 
with shape   (2, 3)
u = 
[ 6  2 -3  5] 
with shape   (4,)
v = 
[ 3  5 -1  4] 
with shape   (4,)
w = 
[1 8 0 5] 
with shape   (4,)


## 2. Vector Operations

u + v =   
u - v =   
alpha * u =    (assume alpha = 6)  
u . v =   
||u|| =   

In [13]:
print "u + v = ", u+v
print "u - v = ", u-v
print "assuming alpha = 6, alpha * u = ", 6*u
print "u . v = ", np.dot(u,v)
print "||u|| = ", np.linalg.norm(u)

u + v =  [ 9  7 -4  9]
u - v =  [ 3 -3 -2  1]
assuming alpha = 6, alpha * u =  [ 36  12 -18  30]
u . v =  51
||u|| =  8.60232526704


## 3. Matrix Operations

In [8]:
print "A + C = ", "not defined"
print "A - C.transpose = \n", A-C.transpose()
print "C.transpose + 3D = \n", C.transpose() + 3*D
print "BA = \n", np.dot(B,A)
print "BA.transpose = ", "not defined"

A + C =  not defined
A - C.transpose = 
[[-4 -7 -3]
 [ 3  6  4]]
C.transpose + 3D = 
[[14  3  3]
 [ 2  7  9]]
BA = 
[[-1 -5 -1]
 [ 2  7  4]]
BA.transpose =  not defined


## Bonus Questions:

In [9]:
print "BC = ", "not defined"
print "CB = \n", np.dot(C,B)
print "B^4 = \n", np.dot(np.dot(B,B), np.dot(B,B))
print "A A.transpose = \n", np.dot(A, A.transpose())
print "D.transpose D = \n", np.dot(D.transpose(), D)

BC =  not defined
CB = 
[[ 5 -6]
 [ 9 -8]
 [ 6 -6]]
B^4 = 
[[ 1 -4]
 [ 0  1]]
A A.transpose = 
[[14 28]
 [28 69]]
D.transpose D = 
[[10 -4  0]
 [-4  8  8]
 [ 0  8 10]]
